### ISSUE TITLE
Authorization Header Needs `Basic` Prefix

### ISSUE THREAD

**Issue by Walexander** [oslo-project/oauth2#1]
When using Basic authentication, I get Unauthorized error from the server.

I believe that's because the Authorization: header needs the string "Basic " before the base64 string.
https://github.com/oslo-project/oauth2/blob/main/src/request.ts#L26

**Comment by pilcrowonpaper** [comment]
Sorry about the late response, I forgot to click "Watch" on all Oslo repos. Should be fixed now!
