### ISSUE TITLE
deprecation confusion

### ISSUE THREAD

**Issue by tcurdt** [oslo-project/oauth2#5]
IIUC this library should be continuance of `oslo/oauth2` ... but there is no `OAuth2Client`

**Comment by pilcrowonpaper** [comment]
It's not a one-to-one change and I don't plan to add a generic OAuth provider. 

https://github.com/oslo-project/oauth2/pull/4#issuecomment-2225017994

**Comment by tcurdt** [comment]
What's the future of `artic`? Is that one safe to use?

https://github.com/pilcrowonpaper/arctic/issues/191
